name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-unit:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: checkout
        uses: actions/checkout@master

      - name: Setup
        run: npm i -g pnpm @antfu/ni

      - name: Lint
        run: nr lint

      - name: Test
        run: nr test:unit

      - name: Coverage
        uses: codecov/codecov-action@v1