name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-unit:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [12.x, 14.x]
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup
        run: npm i -g pnpm @antfu/ni

      - name: Install dependencies
        run: nci

      - name: Lint
        run: nr lint

      - name: Test
        run: nr test:unit

      - name: Coverage
        uses: codecov/codecov-action@v1